package dev.gaddal.utils

import io.github.oshai.kotlinlogging.KotlinLogging
import org.bouncycastle.crypto.generators.Argon2BytesGenerator
import org.bouncycastle.crypto.params.Argon2Parameters
import java.security.SecureRandom

/**
 * Object responsible for hashing and verifying passwords using the Argon2 algorithm.
 *
 * This class uses the Bouncy Castle library's implementation of the Argon2 id algorithm.
 * It provides functions to securely hash passwords and verify them.
 */
object PasswordHasher {
    private val logger = KotlinLogging.logger {}

    // Length of the salt used in password hashing (in bytes)
    private const val SALT_LENGTH = 16

    // Length of the hash generated by Argon2 (in bytes)
    private const val HASH_LENGTH = 32

    /**
     * Hashes a given password using the Argon2 id algorithm.
     *
     * @param password The plaintext password to hash.
     * @return A string containing the salt and the hash, separated by a colon.
     */
    fun hashPassword(password: String): String {
        logger.info { "Hashing password..." }

        // Generate a random salt
        val salt = ByteArray(SALT_LENGTH).apply { SecureRandom().nextBytes(this) }

        // Prepare a byte array to hold the resulting hash
        val hash = ByteArray(HASH_LENGTH)

        // Configure Argon2 parameters
        val params = Argon2Parameters.Builder(Argon2Parameters.ARGON2_id)
            .withSalt(salt)
            .withParallelism(4) // Number of threads to use (degree of parallelism)
            .withMemoryAsKB(65536)  // Memory cost (64 MB)
            .withIterations(3) // Number of iterations
            .build()

        // Initialize the Argon2 generator and create the hash
        Argon2BytesGenerator().apply {
            init(params)
            generateBytes(password.toByteArray(), hash)
        }

        // Return the salt and hash as a single string, separated by a colon
        val result = "${salt.encodeBase64()}:${hash.encodeBase64()}"
        logger.info { "Password hashed successfully." }

        return result
    }

    /**
     * Verifies that a given plaintext password matches a previously hashed password.
     *
     * @param password The plaintext password to verify.
     * @param encodedHash The stored hash (including salt) to check against.
     * @return `true` if the password matches the hash, `false` otherwise.
     */
    fun verifyPassword(password: String, encodedHash: String): Boolean {
        logger.info { "Verifying password..." }

        // Split the encoded hash into salt and hash parts
        val (saltB64, hashB64) = encodedHash.split(":")
        val salt = saltB64.decodeBase64()
        val originalHash = hashB64.decodeBase64()

        // Recreate the Argon2 parameters using the stored salt
        val params = Argon2Parameters.Builder(Argon2Parameters.ARGON2_id)
            .withSalt(salt)
            .withParallelism(4)
            .withMemoryAsKB(65536)  // Memory cost (64 MB)
            .withIterations(3)
            .build()

        // Generate a hash from the input password using the same parameters
        val checkHash = ByteArray(HASH_LENGTH)
        Argon2BytesGenerator().apply {
            init(params)
            generateBytes(password.toByteArray(), checkHash)
        }

        // Compare the newly generated hash with the stored hash
        val isVerified = originalHash.contentEquals(checkHash)
        if (isVerified) {
            logger.info { "Password verified successfully." }
        } else {
            logger.warn { "Password verification failed." }
        }

        return isVerified
    }

    // Helper function to encode a byte array to a Base64 string
    private fun ByteArray.encodeBase64(): String = java.util.Base64.getEncoder().encodeToString(this)

    // Helper function to decode a Base64 string to a byte array
    private fun String.decodeBase64(): ByteArray = java.util.Base64.getDecoder().decode(this)
}
